apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: frontend-build
  namespace: eventplanner
spec:
  source:
    type: Git
    git:
      uri: https://github.com/mofarag122/eventplanner-backend-public.git
      ref: dev
    contextDir: "frontend"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: github-webhook-secret
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: frontend
  namespace: eventplanner